### ISSUE TITLE
[scheduling] Crash when activating a license

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2179]
```
14:21:22.153 (5bdbbcbeb721416a72aa73588f0c2e27) I cloud.calls.server.RpcServer - Incoming call [5bdb]: licenses.provider.ucloud.create (License(id=f941ae4a-656e-4956-be6c-f8db45984448, specification=LicenseSpecification(product=ProductReference(id=tek-ansys, category=tek-ansys, provider=ucloud)), owner=LicenseOwner(createdBy=molinaro@imada.sdu.dk, project=null), createdAt=1612966882137, status=LicenseStatus(state=PREPARING), billing=LicenseBilling(pricePerUnit=0, creditsCharged=0), updates=[], resolvedProduct=License(id=tek-ansys, pricePerUnit=0, category=ProductCategoryId(id=tek-ansys, provider=ucloud), description=Software license, availability=dk.sdu.cloud.accounting.api.ProductAvailability$Available@5df21edf, priority=5, tags=[ANSYS], paymentModel=FREE_BUT_REQUIRE_BALANCE), acl=null))

14:21:22.159 () ERROR jasync.sql.db.postgresql.PostgreSQLConnection - Error , message -> ErrorMessage(fields=[(Severity, ERROR), (V, ERROR), (SQLSTATE, 23503), (Message, insert or update on table "license_instances" violates foreign key constraint "license_instances_server_id_fkey"), (Detail, Key (server_id)=(tek-ansys) is not present in table "license_servers".), (s, app_kubernetes), (t, license_instances), (n, license_instances_server_id_fkey), (File, ri_triggers.c), (Line, 3266), (Routine, ri_ReportViolation)])

14:21:22.159 () ERROR jasync.sql.db.postgresql.PostgreSQLConnection - Error on connection

 com.github.jasync.sql.db.postgresql.exceptions.GenericDatabaseException: ErrorMessage(fields=[(Severity, ERROR), (V, ERROR), (SQLSTATE, 23503), (Message, insert or update on table "license_instances" violates foreign key constraint "license_instances_server_id_fkey"), (Detail, Key (server_id)=(tek-ansys) is not present in table "license_servers".), (s, app_kubernetes), (t, license_instances), (n, license_instances_server_id_fkey), (File, ri_triggers.c), (Line, 3266), (Routine, ri_ReportViolation)])

	at com.github.jasync.sql.db.postgresql.PostgreSQLConnection.onError(PostgreSQLConnection.kt:228) [jasync-postgresql-1.1.3.jar:?]

	at com.github.jasync.sql.db.postgresql.codec.PostgreSQLConnectionHandler.channelRead0(PostgreSQLConnectionHandler.kt:198) [jasync-postgresql-1.1.3.jar:?]

	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-codec-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) [netty-codec-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-codec-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]

	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by DanThrane** [comment]
No longer relevant as of 2021.3.0
