### ISSUE TITLE
[scheduling] app-kubernetes loses connection to K8 and cannot recover

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2288]
The following stacktrace is repeated multiple times in the logs:

```
Exception in thread "pool-4-thread-1375" io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has been expired [url=xxxxxxxx/apis/batch.volcano.sh/v1alpha1/namespaces/app-kubernetes/jobs, connect_timeout=60000 ms] 
	at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:154) 
	at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException$default(HttpTimeout.kt:153) 
	at io.ktor.client.engine.cio.Endpoint.getTimeoutException(Endpoint.kt:208) 
	at io.ktor.client.engine.cio.Endpoint.connect(Endpoint.kt:200) 
	at io.ktor.client.engine.cio.Endpoint$connect$1.invokeSuspend(Endpoint.kt) 
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) 
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113) 
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) 
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
```

This might be related to the other features currently remaining in this epic.

**Comment by DanThrane** [comment]
Assumed to no longer be true for 2021.3.0 release.
