### ISSUE TITLE
advanced search (file) broken

### ISSUE THREAD

**Issue by hschu12** [SDU-eScience/UCloud#2332]
I think this has happend after upgrading java REST API to elastic to newest version. Missing zero_terms_query.

> 16:22:02.538 () I cloud.calls.server.RpcServer - Incoming call [1a17]: indexing.query (QueryRequest(query=FileQuery(roots=[/home/audit1, /projects/11b8088f-c877-4034-b219-543c3fd5296f], fileNameQuery=[ansys], fileNameExact=null, extensions=null, fileTypes=AllOf(allOf=[AnyOf(anyOf=[FILE, DIRECTORY], negate=false)]), fileDepth=null, size=null), sortBy=null, itemsPerPage=25, page=0))
16:22:02.539 () I cloud.indexing.services.ElasticQueryService - {
  "bool" : {
    "filter" : [
      {
        "terms" : {
          "path" : [
            "/home/audit1",
            "/projects/11b8088f-c877-4034-b219-543c3fd5296f"
          ],
          "boost" : 1.0
        }
      },
      {
        "terms" : {
          "fileType" : [
            "FILE",
            "DIRECTORY"
          ],
          "boost" : 1.0
        }
      }
    ],
    "should" : [
      {
        "match_phrase_prefix" : {
          "fileName" : {
            "query" : "ansys",
            "slop" : 0,
            "max_expansions" : 10,
            "zero_terms_query" : "NONE",
            "boost" : 1.0
          }
        }
      }
    ],
    "adjust_pure_negative" : true,
    "minimum_should_match" : "1",
    "boost" : 1.0
  }
}
16:22:02.548 () I cloud.calls.server.RpcServer - Uncaught exception in handler for CallDescription(indexing.query)
16:22:02.548 () I cloud.calls.server.RpcServer - ElasticsearchStatusException[Elasticsearch exception [type=parsing_exception, reason=[match_phrase_prefix] query does not support [zero_terms_query]]]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1900)

**Comment by hschu12** [comment]
Only local - upgrade docker image to version >= 7.10 and run create-fileindex and migrate-apps-to-elastic from backend to fix
