### ISSUE TITLE
[2021.3.0] Failure while monitoring a job

### ISSUE THREAD

**Issue by DanThrane** [SDU-eScience/UCloud#2999]
```
11:12:41.363 () WARNING cloud.app.orchestrator.services.JobMonitoringService - Caught exception while monitoring jobs
11:12:41.364 () WARNING cloud.app.orchestrator.services.JobMonitoringService - dk.sdu.cloud.calls.RPCException: Unable to use all requested resources
at dk.sdu.cloud.accounting.util.ResourceService$retrieveBulk$3.invokeSuspend(ResourceService.kt:241)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by DanThrane** [comment]
Most of the issues, including the on in the original comment, has been fixed. Yet some issues still remain.
